In [1]:
# import modules
import pandas as pd
import tweepy

In [2]:
# function to display data of each tweet
def printtweetdata(n, ith_tweet):
    print()
    print(f"Tweet {n}:")
    print(f"Username:{ith_tweet[0]}")
    print(f"Description:{ith_tweet[1]}")
    print(f"Location:{ith_tweet[2]}")
    print(f"Following Count:{ith_tweet[3]}")
    print(f"Follower Count:{ith_tweet[4]}")
    print(f"Total Tweets:{ith_tweet[5]}")
    print(f"Retweet Count:{ith_tweet[6]}")
    print(f"Tweet Text:{ith_tweet[7]}")
    print(f"Hashtags Used:{ith_tweet[8]}")

In [14]:
def scrape(words, date_since, numtweet):
      
    # Creating DataFrame using pandas
    db = pd.DataFrame(columns=['username', 'description', 'location', 'following',
                               'followers', 'totaltweets', 'retweetcount', 'text', 'hashtags'])
      
    # We are using .Cursor() to search through twitter for the required tweets.
    # The number of tweets can be restricted using .items(number of tweets)
    tweets = tweepy.Cursor(api.search_tweets, q=words, lang="en",
                           since=date_since, tweet_mode='extended').items(numtweet)
     
    # .Cursor() returns an iterable object. Each item in 
    # the iterator has various attributes that you can access to 
    # get information about each tweet
    list_tweets = [tweet for tweet in tweets]
      
    # Counter to maintain Tweet Count
    i = 1  
      
    # we will iterate over each tweet in the list for extracting information about each tweet
    for tweet in list_tweets:
        username = tweet.user.screen_name
        description = tweet.user.description
        location = tweet.user.location
        following = tweet.user.friends_count
        followers = tweet.user.followers_count
        totaltweets = tweet.user.statuses_count
        retweetcount = tweet.retweet_count
        hashtags = tweet.entities['hashtags']
          
        # Retweets can be distinguished by a retweeted_status attribute,
        # in case it is an invalid reference, except block will be executed
        try:
            text = tweet.retweeted_status.full_text
        except AttributeError:
            text = tweet.full_text
        hashtext = list()
        for j in range(0, len(hashtags)):
            hashtext.append(hashtags[j]['text'])
          
        # Here we are appending all the extracted information in the DataFrame
        ith_tweet = [username, description, location, following,
                     followers, totaltweets, retweetcount, text, hashtext]
        db.loc[len(db)] = ith_tweet
          
        # Function call to print tweet data on screen
        printtweetdata(i, ith_tweet)
        i = i+1
    filename = 'scraped_tweets1.csv'
      
    # we will save our database as a CSV file.
    db.to_csv(filename)
  
  
if __name__ == '__main__':
      
    # Enter your own credentials obtained 
    # from your developer account
    consumer_key = "kGBh7pTKLQi0MFZMI2ykfgznA"
    consumer_secret = "1VuWbtqQKhTww9VkK3d6nzdqZxvTPA2DOrAsLsqgZnB3c4FSxx"
    access_key = "993185396-5Z4IXNL0k6KoUN7QA4uNKEYjgkaupTNMsHyWnVQL"
    access_secret = "bVWEOwCDqxi0IKZNLOdZ1wtQpM8L9siZfNVCgFO8p3aWD"
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    api = tweepy.API(auth)
      
    # Enter Hashtag and initial date
    print("Enter Twitter HashTag to search for")
    words = input()
    print("Enter Date since The Tweets are required in yyyy-mm--dd")
    date_since = input()
      
    # number of tweets you want to extract in one run
    numtweet = 100  
    scrape(words, date_since, numtweet)
    print('Scraping has completed!')

Enter Twitter HashTag to search for
#diwali
Enter Date since The Tweets are required in yyyy-mm--dd
2021-11-01

Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since

Tweet 1:
Username:Dhanteras, also known as Dhantrayodashi marks the beginning of the festival of light, Diwali.May you be showered with health, wealth and happiness on this auspicious occasion.

#Dhanteras2021 #Dhanteras #HappyDhanteras #Diwali #Abeonaz #AbeonazCommunity
Description:['Dhanteras2021', 'Dhanteras', 'HappyDhanteras', 'Diwali', 'Abeonaz', 'AbeonazCommunity']

IndexError: list index out of range

In [12]:
df = pd.read_csv("scraped_tweets1.csv")
df

,Unnamed: 0,username,description,location,following,followers,totaltweets,retweetcount,text,hashtags
0,0,CollabMerch,NaN,NaN,36,0,28,0,Happy Dhanteras to everyone 🪔\nMay Dhanteras E...,"['happydhanteras', 'shubh', 'dhanteras', 'diwa..."
1,1,suryatej_borra,NaN,"Hyderabad, India",831,786,20070,191,The splendid ancient city of Lord Rama lights ...,"['Diwali', 'Dhanteras', 'धनतेरस', 'Diwali2021']"
2,2,Tap_a_Gain,"Consultant : Advertising, Digital, Social Medi...",Mumbai INDIA,655,282,866,0,"Wellwishers, wishing you all a very happy #diw...","['diwali', 'followus']"
3,3,nashik_feed,This is an Experimental Bot. Follow @Nashik_fe...,"Nashik, India",480,2314,110509,1,𝐇𝐚𝐩𝐩𝐲 𝐃𝐡𝐚𝐧𝐭𝐞𝐫𝐚𝐬 -\n\nFor more updates please c...,"['Diwali', 'Dhanteras', 'Dhanotrayodashi']"
4,4,vishal_z3,"Vagabond: Yesterday, Today & Tomorrow | https:...",NaN,579,24,2778,0,@rishibagree Halloween celebrated in #Dubai du...,"['Dubai', 'T20Worldcup', 'Diwali']"
...,...,...,...,...,...,...,...,...,...,...
95,95,MODIGAURAV82,NaN,NaN,160,81,26852,2475,US lawmaker to introduce Bill to make #Diwali ...,['Diwali']
96,96,musale_vishnu,NaN,"Pune, India",430,47,5608,126,Don't let Greedy &amp; Seculars dominate our H...,"['Diwali', 'धनतेरस', 'Dhanteras', 'धनत्रयोदशी'..."
97,97,vipinpratap20,धर्मो रक्षति रक्षितः\nआप धर्म की रक्षा करें धर...,Jaipur,157,21,3605,2475,US lawmaker to introduce Bill to make #Diwali ...,['Diwali']
98,98,thebrajeshs,"🇮🇳भारत मेरा देश, भारत मेरी शान।हर हर महादेव!!🚩...",अखंड भारत,4395,9167,254258,264,Odisha govt allows sale and use of Green-Crack...,['Diwali']
99,99,Bishal69520801,NaN,NaN,153,247,37398,36,#Exclusive 🤩🔥\n\nScroll down to know how your ...,"['Exclusive', 'Diwali', 'Diwali2021']"